### ISSUE TITLE
The script stopped when doesnt find a hit. Multifasta file

### ISSUE THREAD

**Issue by okapick** [T-B-F/pyHCA#2]
Good morning. The script stopped, it tell me to find less stringent parameters. I wonder if the parameters is about the hhblist command or about other command phmmer. I am working with a multifasta file.

the problematic sequences is this:
>Problematic
SQVVRVFVVLRAARAGRLFFMRSREKSTRPCRNRSNLQRFLFVNRVYIEGYV*

```
hhblits -i Unigenes_anotation_trial2_desde1731/workdir_protein_6/dom_0/query_0.fasta -d hhsuite/uniclust30_2018_08/uniclust30_2018_08 -scores Unigenes_anotation_trial2_desde1731/workdir_protein_6/dom_0/query_hhblits.scores -o Unigenes_anotation_trial2_desde1731/workdir_protein_6/dom_0/query_hhblits.hhr   -cov 10 -e 1.0 -cpu 30 
Done in 1004.9879713058472
hhblits -i Unigenes_anotation_trial2_desde1731/workdir_protein_7/dom_0/query_0.fasta -d hhsuite/uniclust30_2018_08/uniclust30_2018_08 -scores Unigenes_anotation_trial2_desde1731/workdir_protein_7/dom_0/query_hhblits.scores -o Unigenes_anotation_trial2_desde1731/workdir_protein_7/dom_0/query_hhblits.hhr   -cov 10 -e 1.0 -cpu 30 
Unable to find any targets with hhblits in database hhsuite/uniclust30_2018_08/uniclust30_2018_08
Please try less stringent parameters or a different database
```

**Comment by okapick** [comment]
Sorry. It me again. I wonder how can i modifed the script to continue analyzing the others sequences in the multifasta file.

>   ```
  # perform search method on each selected parts
        targets, alltargetids = search_domains(query, positions, params.targetdb, configuration, query_workdir)
        if alltargetids == []:
            print("Unable to find any targets with hhblits in database {}".format(params.targetdb), file=sys.stderr)
            #print("with parameters {}".format(params.hhblitsparams), file=sys.stderr)
            print("Please try less stringent parameters or a different database", file=sys.stderr)
            with open(output_file, "w") as outf: # output to output file
                outf.write("# Unable to find any targets with hhblits in database {}\n".format(params.targetdb))
                #outf.write("# with parameters {}\n".format(params.hhblitsparams))
                outf.write("# Please try less stringent parameters or a different database\n")
        
            sys.exit(0)
I am not so geeky. I am cript-kiddie. I wonder if i need to delete the script part where put sys.exit(0).

Regards.
```

**Comment by T-B-F** [comment]
Hi, it means that the hhblits command didn't find any hit of your fasta sequence on the database used.
The command was "hhblits -i Unigenes_anotation_trial2_desde1731/workdir_protein_6/dom_0/query_0.fasta -d hhsuite/uniclust30_2018_08/uniclust30_2018_08 -scores Unigenes_anotation_trial2_desde1731/workdir_protein_6/dom_0/query_hhblits.scores -o Unigenes_anotation_trial2_desde1731/workdir_protein_6/dom_0/query_hhblits.hhr   -cov 10 -e 1.0 -cpu 30" 
So you could try to increase the evalue to perhaps find some match of your sequence (you can look at hhblits manual for a list of available option). But keep in mind that sequences you may also increase the number of false positive (sequences without any kind of evolutionary relationships).

**Comment by T-B-F** [comment]
You can pass a config file using the --config option, directly modify or copy and edit the tremolo_config.dat file.

**Comment by T-B-F** [comment]
You can add any key/value option as long as the option exist in hhblits.

**Comment by okapick** [comment]
Thanks so much for the advise.. I dont think to reduce the evalue.
