### ISSUE TITLE
Biopython Alphabet package has been removed

### ISSUE THREAD

**Issue by cgpapado** [T-B-F/pyHCA#4]
Due to biopython update the package Alphabet does not exist any more . As a result the script does not work any more and gives the following message: 

ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by T-B-F** [comment]
Could you provide me an error line number?

**Comment by cgpapado** [comment]
I fixed the problem myself to my local version. 
What I did was:
1. To delete the line **16**: "from Bio.Alphabet import IUPAC"
2. Replace the line **633**: “prot_alphabet = set(IUPAC.protein.letters)” with “ prot_alphabet = ‘ACDEFGHIKLMNPQRSTVWY’ “
in the **HCA.py** script. 
After these corrections the program is installed and runs with no problems on my computer!

**Comment by T-B-F** [comment]
Ok, I fixed it too with a more stable fix which should work with old and
new version of biopython

**Comment by T-B-F** [comment]
fixed in 16dee60
